version: '3'
volumes:
  db:
networks:
  fvapp:
    driver:
      bridge
services:
  api:
    build: .
    volumes:
      - ./:/api
    ports:
      - "3030:3030"
    depends_on:
      - db
    networks:
      - fvapp
  db:
    image: mongo:latest
    volumes:
      - "db:/data/db"
    ports:
      - 27017:27017
    networks:
      - fvapp